project_name: sparkle

archives:
  - id: sparkle
    files:
      - LICENSE
      - PATENTS
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"

brews:
  - name: sparkle
    commit_author:
      name: Kamil Samigullin
      email: kamil@samigullin.info
    description: |
      ✨ Sparkle service. The personal development framework
      and Personal Knowledge Management platform.
    folder: Formula
    homepage: https://sparkle.wiki/
    repository:
      owner: octolab
      name: homebrew-tap
    install: |
      bin.install "sparkle"

      output = Utils.popen_read("#{bin}/sparkle completion bash")
      (bash_completion/"sparkle").write output

      output = Utils.popen_read("#{bin}/sparkle completion fish")
      (fish_completion/"sparkle.fish").write output

      output = Utils.popen_read("#{bin}/sparkle completion zsh")
      (zsh_completion/"_sparkle").write output

      prefix.install_metafiles
    test: |
      system "#{bin}/sparkle version"

builds:
  - id: sparkle
    binary: sparkle
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: withsparkle
    name: service
